theme: jekyll-theme-slate
title: Email Thread Summarization with T5
tagline: Summarize Email Threads through Transfer Learning
authors:
  saif:
    name: 'Saifullah Katpar'
  asma:
    name: 'Asma Rehman Ali'
