theme: jekyll-theme-slate
title: Email Thread Summarization with T5
tagline: Summarize Email Threads through Transfer Learning
description: 
      Summarize Email Threads through Transfer Learning
      
      By Asma Damani, Saifullah
